sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dIAdTh6PMP3dt6ogzaVWQPPCtRsbVj32vkBGuBl2EeBrmKDK3VipkQbbuBBIJs2zjWNek23h4h9Rp3xqBTJWRGd35aedH3LDrcs1Hf0Xa8S0vgLdTV+RVwYpd7Vbq+EN1XmUQiV/DCXWQAvBoTQJfKkFTKiOr0waGG2z0SK3S4rNg+ydvjNWSrvRWDmcJLZbDKAuQX8TGXj0yhXETYX8skfa5RPTtJbZjFKeJTElL56CDK5cOw1tQwPa36W/HVo2L/FQWtBMPV1D/4TBHEPIQsVzg8agFBTfVBCkalSoGbM4PPtgtwwR1GH44wBvVEVX8lSjCT14/HbTjCR5Z2NRTM3dpjz5E/jpZQAAn1kvmY9J+e1C6evKlvJJdWymBowOnSleVDU/eUxvPGospt1gWhAlewVNHITChajwC2Fxtt34YJqr82imkIBYq+vrRInIKDAf03PICMpVRLMFmMsu29Z7Jc38DfJeoElvEq3fqRk/Yk4p+RqfF496FZ+bbQV987gjXpbfqVO4EwFcszY4GzWedELYIPYkXxuhUOPUMVafCTdAZ8uwfI3TwUqyiu79zC13lIVgs6gq4Y7btwCmtTi3SAm1jz7xyIQ04m/0jn3UG66OIhdevq7c+tcVRTi+4bmQK3mQzp44jAiYutCgVwYVXReBPpgX0DSDnQLeg+c=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Memoirs-of-Jacques-Casanova-de-Seingalt-1725-1798.-Volume-15--With-Voltaire_2965
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy